pipeline {
    agent any
    
    stages {
        stage('Copy Config Files') {
            steps {
                sh """
                ./virtual_env.sh
                """
            }
        }
    }
}
